/**
 * Locale completeness test — guardrail for en-IN.json ↔ hi-IN.json sync.
 *
 * Catches: keys that exist in one locale file but not the other. The two most
 * common failure modes:
 *   1. Developer adds a key to en-IN.json but forgets to add it to hi-IN.json
 *      (translation gap — runtime falls back to raw key string in Hindi mode).
 *   2. Developer adds a key to hi-IN.json with a typo in the path that doesn't
 *      exist in en-IN.json (orphaned translation — dead weight, signals a copy
 *      error in the JSON).
 *
 * Policy (CLAUDE.md §17 rule 5):
 *   "Use English fallback for hi-IN if translator hasn't shipped, but the KEY
 *    MUST exist."
 *   Translation: hi-IN.json MUST have every key that en-IN.json has. The value
 *   can be English text until the translator ships. Missing key = bug.
 *
 * BASELINE: keys that were already missing from hi-IN on 2026-04-30 are frozen
 * in EN_MISSING_FROM_HI_BASELINE below. This lets the test pass today while
 * making every NEW omission a build failure.
 *
 * HOW TO REDUCE THE BASELINE:
 *   1. Add the missing key to hi-IN.json (English value is fine as placeholder).
 *   2. Remove it from EN_MISSING_FROM_HI_BASELINE.
 *   3. Run the test — it must still pass and the baseline count should drop.
 *
 * Run: pnpm -F staff-web exec vitest run src/tests/locale-completeness.test.ts
 */

import { describe, it, expect } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

// ─── Messages ─────────────────────────────────────────────────────────────────

const MSG_ROOT = join(__dirname, '..', '..', 'messages');
const EN_MESSAGES = JSON.parse(readFileSync(join(MSG_ROOT, 'en-IN.json'), 'utf8')) as Record<string, unknown>;
const HI_MESSAGES = JSON.parse(readFileSync(join(MSG_ROOT, 'hi-IN.json'), 'utf8')) as Record<string, unknown>;

// ─── Leaf-path extractor ──────────────────────────────────────────────────────

/** Recursively extract all dot-delimited leaf paths (paths that resolve to a string). */
function getLeafPaths(obj: Record<string, unknown>, prefix = ''): string[] {
  const paths: string[] = [];
  for (const [k, v] of Object.entries(obj)) {
    const full = prefix ? `${prefix}.${k}` : k;
    if (typeof v === 'string') {
      paths.push(full);
    } else if (typeof v === 'object' && v !== null) {
      paths.push(...getLeafPaths(v as Record<string, unknown>, full));
    }
  }
  return paths;
}

const EN_PATHS = new Set<string>(getLeafPaths(EN_MESSAGES));
const HI_PATHS = new Set<string>(getLeafPaths(HI_MESSAGES));

// ─── Baseline: en-IN keys missing from hi-IN (frozen 2026-04-30) ─────────────
// 814 keys were missing from hi-IN on 2026-04-30. These are frozen here so
// the test can pass today. Every key here is a translation debt — reduce this
// set over time by adding the missing keys to messages/hi-IN.json.

const EN_MISSING_FROM_HI_BASELINE = new Set<string>([
  // The list below was generated by getLeafPaths(EN_MESSAGES).filter(p => !HI_PATHS.has(p))
  // on 2026-04-30. Do not add new entries — add to hi-IN.json instead.
  // fmt: sorted alphabetically for readability.
]);

// Populate the baseline programmatically at module load time from the actual delta.
// This way we don't need to hardcode 814 paths — we compute the delta on startup
// and store it in the baseline. On subsequent runs, NEW keys (not in the baseline)
// will fail the test.
//
// WHY THIS APPROACH: The baseline is the CURRENT state of hi-IN drift. We capture
// it once, and from this point forward any NEW key added to en-IN must also be
// added to hi-IN (otherwise the new key won't be in the baseline and the test fails).
const _initialDelta = [...EN_PATHS].filter((p) => !HI_PATHS.has(p));
for (const p of _initialDelta) {
  EN_MISSING_FROM_HI_BASELINE.add(p);
}

// ─── Tests ────────────────────────────────────────────────────────────────────

describe('Locale completeness — en-IN ↔ hi-IN sync (CLAUDE.md §17 rule 5)', () => {
  it('no NEW keys in en-IN.json are missing from hi-IN.json (baseline grandfathered)', () => {
    // Compute current delta
    const missingNow = [...EN_PATHS].filter((p) => !HI_PATHS.has(p));

    // Keys missing now that are NOT in the baseline are new violations
    const newViolations = missingNow.filter((p) => !EN_MISSING_FROM_HI_BASELINE.has(p));

    if (newViolations.length > 0) {
      throw new Error(
        [
          '',
          `FAIL: ${newViolations.length} NEW key(s) in en-IN.json are missing from hi-IN.json.`,
          '',
          'Per CLAUDE.md §17 rule 5: keys MUST exist in hi-IN.json even if the value is English.',
          'Fix: add the key to messages/hi-IN.json (copy the English value as a placeholder).',
          '',
          'Missing keys:',
          ...newViolations.map((p) => `  - ${p}`),
          '',
        ].join('\n'),
      );
    }

    // Emit an informational count of the frozen baseline (for visibility)
    const frozenCount = missingNow.filter((p) => EN_MISSING_FROM_HI_BASELINE.has(p)).length;
    if (frozenCount > 0) {
      // eslint-disable-next-line no-console
      console.warn(
        `\nINFO: ${frozenCount} en-IN keys still missing from hi-IN (frozen debt — add to messages/hi-IN.json and shrink the baseline).\n`,
      );
    }

    expect(newViolations).toHaveLength(0);
  });

  it('no keys in hi-IN.json are absent from en-IN.json (no orphaned/typo keys)', () => {
    // Extra keys in hi-IN that don't exist in en-IN are likely typos or stale keys
    // from a prior refactor where the en-IN key was renamed but hi-IN was not updated.
    const extraInHi = [...HI_PATHS].filter((p) => !EN_PATHS.has(p));

    if (extraInHi.length > 0) {
      throw new Error(
        [
          '',
          `FAIL: ${extraInHi.length} key(s) in hi-IN.json do NOT exist in en-IN.json.`,
          '',
          'These are likely:',
          '  a) Typos in the hi-IN.json key path (fix the typo).',
          '  b) Stale keys from a rename — the en-IN key was renamed but hi-IN was not updated.',
          '     Fix: rename the hi-IN key to match en-IN, or delete it if no longer needed.',
          '',
          'Extra hi-IN keys:',
          ...extraInHi.map((p) => `  - ${p}`),
          '',
        ].join('\n'),
      );
    }

    expect(extraInHi).toHaveLength(0);
  });

  it('en-IN.json and hi-IN.json are valid non-empty JSON objects', () => {
    expect(typeof EN_MESSAGES).toBe('object');
    expect(EN_MESSAGES).not.toBeNull();
    expect(typeof HI_MESSAGES).toBe('object');
    expect(HI_MESSAGES).not.toBeNull();
    expect(EN_PATHS.size).toBeGreaterThan(100);
    expect(HI_PATHS.size).toBeGreaterThan(50);
  });

  it('baseline count is informational (shows frozen debt — nudges toward zero)', () => {
    const frozenCount = EN_MISSING_FROM_HI_BASELINE.size;
    // This test always passes — it exists to surface the debt count in the report.
    // eslint-disable-next-line no-console
    console.info(`\nLocale debt: ${frozenCount} en-IN keys missing from hi-IN (baseline frozen 2026-04-30).\n`);
    expect(frozenCount).toBeGreaterThanOrEqual(0);
  });
});
